export const copy = {
  brand: {
    name: "DriveFlow",
    tagline: "Location de voitures, simplement.",
  },
  nav: {
    home: "Accueil",
    cars: "Voitures",
    howItWorks: "Comment ça marche",
    contact: "Contact",
    book: "Réserver",
    bookLong: "Réserver une voiture",
    openMenu: "Ouvrir le menu",
    closeMenu: "Fermer le menu",
    primary: "Navigation principale",
  },
  header: {
    skipToContent: "Aller au contenu",
  },
  footer: {
    serviceArea: "Zones desservies",
    legal: "Mentions légales",
    privacy: "Confidentialité",
    rights: "Tous droits réservés.",
    placeholderLegal: "Pages légales à venir.",
  },
  whatsapp: {
    label: "WhatsApp",
    floatingLabel: "WhatsApp",
    defaultMessage: "Bonjour, je souhaite louer une voiture avec DriveFlow.",
    carMessage: (name: string) => `Bonjour, je suis intéressé par la ${name} chez DriveFlow.`,
  },
  home: {
    title: "Accueil",
    kicker: "Location de voitures au Maroc",
    heading: "Prenez la route.\nOn s’occupe du reste.",
    subheading:
      "Choisissez votre voiture, vos dates et vos lieux. Envoyez votre demande : notre équipe vous contacte rapidement pour confirmer la disponibilité.",
    reassurance: "Envoyez votre demande. Notre équipe vous contacte rapidement pour confirmer la disponibilité.",
    ctaCars: "Voir les voitures",
    ctaBook: "Réserver maintenant",
    featuredKicker: "Sélection",
    featuredTitle: "Véhicules du moment",
    featuredIntro: "Une gamme claire, du quotidien au voyage d’affaires.",
    whyKicker: "L’agence",
    whyTitle: "Pourquoi DriveFlow",
    whyItems: [
      {
        title: "Une demande, un échange",
        body: "Pas de compte, pas de parcours interminable. Vous écrivez, nous rappelons.",
      },
      {
        title: "Prise en charge flexible",
        body: "Aéroports, centres-villes et ports : vous indiquez le lieu, nous organisons.",
      },
      {
        title: "Une personne au bout du fil",
        body: "La disponibilité se confirme avec vous, par téléphone ou WhatsApp.",
      },
      {
        title: "Un parc lisible",
        body: "Citadines, SUV et berlines — l’essentiel, sans catalogue brouillon.",
      },
    ],
    howTitle: "Comment ça marche",
    howCta: "Commencer ma réservation",
    steps: [
      {
        title: "Choisissez votre voiture",
        body: "Parcourez le parc et ouvrez la fiche du véhicule qui vous convient.",
      },
      {
        title: "Indiquez vos dates et lieux",
        body: "Départ, retour, aéroport ou ville : tout tient sur un formulaire.",
      },
      {
        title: "Nous vous contactons pour confirmer",
        body: "L’agence reçoit votre demande et revient vers vous pour valider la disponibilité.",
      },
    ],
    locationsKicker: "Maroc",
    locationsTitle: "Où vous récupérer",
    locationsIntro: "Les principaux aéroports et centres-villes que nous desservons.",
    locationsCta: "Choisir un lieu",
    finalTitle: "Votre prochaine route commence ici.",
    finalBody: "Choisissez un véhicule et envoyez votre demande en quelques minutes. Nous confirmons ensuite avec vous.",
    finalCta: "Réserver une voiture",
    searchTitle: "Préparer ma demande",
    searchPickup: "Lieu de départ",
    searchStart: "Date de départ",
    searchEnd: "Date de retour",
    searchCta: "Voir les voitures",
    searchHint: "Cela ouvre le formulaire — la disponibilité sera confirmée par l’agence.",
  },
  cars: {
    title: "Voitures",
    heading: "Nos voitures",
    intro:
      "Une sélection pour la ville, la route, les déplacements d’affaires et les arrivées d’aéroport.",
    viewDetails: "Voir les détails",
    viewVehicle: "Voir le véhicule",
    bookNow: "Réserver",
    bookThis: "Réserver ce véhicule",
    from: "À partir de",
    perDay: "/ jour",
    empty: "Aucun véhicule ne correspond à ces critères.",
    reset: "Réinitialiser les filtres",
    notFound: "Ce véhicule n’est pas dans le catalogue.",
    filters: "Filtres",
    category: "Catégorie",
    allCategories: "Toutes",
    transmission: {
      label: "Boîte",
      all: "Toutes",
      automatic: "Automatique",
      manual: "Manuelle",
    },
    seats: "Places",
    allSeats: "Toutes",
    sort: "Trier",
    sortDefault: "Par défaut",
    sortPriceAsc: "Prix croissant",
    sortPriceDesc: "Prix décroissant",
    categories: {
      economy: "Économique",
      suv: "SUV",
      luxury: "Berline",
      van: "Ludospaces",
      sport: "Sport",
    },
    specs: {
      seats: "places",
      doors: "portes",
      luggage: "bagages",
      ac: "Climatisation",
      fuel: "Carburant",
    },
    related: "Autres véhicules",
    stickyBook: "Réserver",
  },
  booking: {
    title: "Demande de réservation",
    heading: "Votre demande",
    intro:
      "Envoyez votre demande. Notre équipe vous contacte rapidement pour confirmer la disponibilité.",
    notice: "Le prix final et la disponibilité seront confirmés par notre équipe.",
    groups: {
      contact: "Vos coordonnées",
      vehicle: "Votre véhicule",
      pickup: "Départ",
      return: "Retour",
      extra: "Informations complémentaires",
    },
    fields: {
      name: "Nom complet",
      phone: "Téléphone / WhatsApp",
      email: "Email",
      car: "Voiture",
      pickupLocation: "Lieu de départ",
      pickupDate: "Date de départ",
      pickupTime: "Heure de départ",
      returnLocation: "Lieu de retour",
      returnDate: "Date de retour",
      returnTime: "Heure de retour",
      message: "Message (optionnel)",
      chooseCar: "Choisir une voiture",
      chooseLocation: "Choisir un lieu",
    },
    submit: "Envoyer ma demande",
    submitting: "Envoi en cours…",
    phaseNotice:
      "La réception automatique des demandes sera activée à l’étape suivante. Vérifiez vos informations : dès qu’elle le sera, ce bouton transmettra réellement votre demande.",
    invalidBanner: "Merci de corriger les champs indiqués.",
    confirmationTitle: "Demande envoyée",
    confirmationHeading: "Demande envoyée",
    confirmationBody:
      "Merci. Votre demande a bien été transmise. Notre équipe vous contactera rapidement pour confirmer la disponibilité et finaliser votre réservation.",
    backHome: "Retour à l’accueil",
    viewCars: "Voir les voitures",
    errors: {
      customerName: "Indiquez votre nom complet.",
      customerPhone: "Indiquez un numéro marocain valide (06, 07 ou +212).",
      customerEmail: "Indiquez un email valide.",
      carId: "Choisissez un véhicule.",
      pickupLocationId: "Choisissez un lieu de départ.",
      returnLocationId: "Choisissez un lieu de retour.",
      pickupDate: "Indiquez une date de départ.",
      pickupTime: "Indiquez une heure de départ.",
      returnDate: "La date de retour doit être après le départ.",
      returnTime: "Indiquez une heure de retour.",
      past: "La date de départ ne peut pas être dans le passé.",
      message: "Le message est trop long.",
    },
  },
  common: {
    close: "Fermer",
  },
} as const;

export type Copy = typeof copy;
